### ISSUE TITLE
Navigation doesn't hide on mobile and you can't close it

### ISSUE THREAD

**Issue by carlosepp** [alphasights/paint#114]
![photo_2015-09-15_10-21-12](https://cloud.githubusercontent.com/assets/497142/9880943/7eb74072-5b93-11e5-929e-7210f56c2dbc.jpg)

Also it would be nice to check it out and add the touch for smooth scrolling

**Comment by deioo** [comment]
@carlosepp closing?

**Comment by carlosepp** [comment]
not yet, gotta test on dragon, we still need the autoprefixer there to be able to test

**Comment by deioo** [comment]
https://github.com/postcss/autoprefixer

**Comment by carlosepp** [comment]
testing this https://github.com/alphasights/dragon/pull/540

**Comment by carlosepp** [comment]
it worked :)
