### ISSUE TITLE
Consistent cancel actions 

### ISSUE THREAD

**Issue by nolvera** [alphasights/paint#140]
I've seen most of the cancel actions as red. But, why is this one is blue?  I think it should be consistent.
 

<img width="1048" alt="screen shot 2015-10-26 at 9 09 23 am" src="https://cloud.githubusercontent.com/assets/8930111/10731730/28472342-7bcd-11e5-8a0e-952d770640a5.png">

**Comment by deioo** [comment]
App-specific issue, closing
