### ISSUE TITLE
Files exposed by main key in bower assets are usually compiled for distribution

### ISSUE THREAD

**Issue by daemonsy** [alphasights/paint#18]
A common pattern we do with `rails-assets-<bower>` libraries

```ruby
# In Gemfile
gem 'rails-assets-paint'
```

```sass
# In our SASS files
//= require paint

```

This won't work because paint is a SCSS file referencing its individual components. It's quite a common pattern to expose fully compiled CSS/JS files in the main key of bower.json. It seems that our Ember CLI projects are requiring the files from the bower_components directory directly. 

In that case, can I add a build step to build something like `dist/paint.css` and exposing it in the main key?

**Comment by matteodepalo** [comment]
A build step implemented with broccoli seems to be a good solution.

**Comment by matteodepalo** [comment]
The problem with compiling the scss to a global css is that you would lose all the mixins and goodies that come with scss. What was the error you were getting? Because if it's only the foundation css that cannot be found than we can solve it in other ways (like including foundation in the code).

**Comment by daemonsy** [comment]
Yup, exactly as you said, hence we need some way to expose the SCSS files in a structured way. Currently, `main` exposes `paint.scss`. 

Consider the typical way we consume a bower library with rails-assets. 

```ruby
# In Gemfile
gem 'rails-assets-paint'
```

```sass
# In our SASS files
//= require paint
```
The sass bit generates an error because `paint.scss` is missing all it dependencies. So it makes the `main` key broken for rails-assets. 

### Different types of workflow

**Rails, using SASS** 
The `paint-rails` gem currently exposes all the SCSS files. This works pretty well and it's the most typical way asset gems work. The only thing is that paint-rails has a build step that is kind of [hacky](https://github.com/alphasights/paint-rails/blob/master/Rakefile#L7) where we copy in all the assets from paint. For example, images and different CSS folders are at the root level, so we have to make sure we copy in the right folders. This build step might be better done in paint and paint-rails just have to expose the right `dist` folders. 

**rails-assets-<gem>**
Can the `rails-assets` idiom expose more than 1 file for `main`? If not, why don't we just compile `paint.css` and expose it in main for consumers who don't want the SCSS goodies. 

**Bower - Ember CLI**
We're already able to directly import the source files, so no big worries here.

**Comment by matteodepalo** [comment]
The problem is that paint does very little to the css, it's mostly a library that exposes mixins and placeholders, so unless you use them explicitly in your scss files it won't do much for you. I think we should simply create a build step that concatenates files, but I'm not an expert in this. I'll investigate a bit more and get back to you.
